### ISSUE TITLE
pages - Editor speichert keinen Inhalt

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#13]
Jetzt erscheint ein Editor :)
![image](https://user-images.githubusercontent.com/115038502/193918921-16da1d72-9c0f-4b6e-95f0-84cbb12f3867.png)

Wenn ich aber in den Editor etwas Text eingebe und auf update drücke, ist bei erneuten aufrufen der Seite kein Text zu sehen. Auch in der Tabellenansicht der Pages ist in der Spalte Editor nichts zu sehen.

**Comment by anjunar** [comment]
Lag daran das ich kein deep-copy von dem default Value gemacht habe. Ist gefixt.
