### ISSUE TITLE
Navigations- / Chatleiste Oben

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#14]
![image](https://user-images.githubusercontent.com/115038502/193920873-2ef01ed0-6e09-4e58-875c-f7d6b0a8d387.png)

Wenn man die Maus über das Wort Chat bewegt verwandelt sich der Zeiger nicht in die Zeigende Hand wie bei anderen Links sondern in einen Schrreibcourser. (Browser Edge)

**Comment by anjunar** [comment]
Ist gefixt :-)

**Comment by FireFoxX79** [comment]
Im Nachtest OK.
