### ISSUE TITLE
Verlinkung setzten funktioniert nicht

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#16]
Wollten auf den Gelb markierten Text (Bild 1) eine Verlinkung setzen. Dazu wurde der entsprechende Bereich markiert, Es öffnet sich auch ein Menü (Bild 2). Aber nach Klick auf OK ist kein Link erkennbar. Bild 3
![image](https://user-images.githubusercontent.com/115038502/194144011-d64b9033-3acf-4b2b-bebd-c4b3247d1893.png)

![image](https://user-images.githubusercontent.com/115038502/194144506-a593e7c0-bd80-4fa8-9699-437c1d9a5792.png)

![image](https://user-images.githubusercontent.com/115038502/194144984-24518abb-aa8c-4d5d-aab4-7a4e4c7436f9.png)

**Comment by anjunar** [comment]
Fixed in v1.01 alpha

**Comment by FireFoxX79** [comment]
Im Nachtest OK.
