### ISSUE TITLE
Pages - Editor - Funktion Select All - Wählt gesamte Seite aus

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#17]
Wenn der Courser nicht im Editor selber steht wird die Gesamte Website Selektiert. Soll das so sein, oder sollte es keinen Fokus im Editor geben dieser nicht automatisch durch die Anwendung gesetzt werden, so das wieder nur noch der Inhalt des Editor markiert wird (Bild 2)? 
![image](https://user-images.githubusercontent.com/115038502/194146904-61e66409-e1ff-4cfd-a37f-9eac0653a471.png)

![image](https://user-images.githubusercontent.com/115038502/194146784-1c4f7162-ada6-4dcb-bfe7-dfcb08f83227.png)

**Comment by anjunar** [comment]
Fixed in v1.01 alpha

**Comment by FireFoxX79** [comment]
Im Nachtest OK
