### ISSUE TITLE
Pages - Editor - Funktion Fett / Kursiv ....

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#18]
Für alle 5 Funktionen gilt wenn ich einen markierten Text Wähle und jetzt zum Beispiel Fett aktiviere wird das Icon grünlich als aktiv dargestellt. Soweit OK. Aber wenn ich im selben schritt Fett wieder deaktivieren will wirkt sich diese auf den Text aus (Soll ja auch so sein), aber leider wird die farbliche Markierung nicht wieder entfernt, so das man denken könnte es wäre doch noch aktiv. 
![image](https://user-images.githubusercontent.com/115038502/194149441-9b84d084-4cee-46e0-9e3d-3de6c8c6c2b5.png)

**Comment by anjunar** [comment]
Fixed in v1.01 alpha

**Comment by FireFoxX79** [comment]
Im Nachtest OK.
