### ISSUE TITLE
Pages ohne Inhalt und Language lassen sich nicht öffnen.

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#23]
Wenn ich Versuch die Seite erneut zu betreten, passiert zwar das der Link im Browser richtig angezeigt wir auf die Seite die man wechseln würde, aber die Seite wir anscheint nicht neu geladen. Wenn man dann den Browser  zum neuladen zwingt wird eine Leere Seite (Bild 2) dargestellt.

![image](https://user-images.githubusercontent.com/115038502/194727975-4d792b79-20be-4502-ac3d-76d460c1ca76.png)

![image](https://user-images.githubusercontent.com/115038502/194728081-961eaf3b-c184-4629-8fe3-8f4e48676b38.png)

**Comment by anjunar** [comment]
Öffne mal das nächste mal die Entwickler Konsole und sag mir welche Fehlermeldung das Request zurück gibt.

Wahrscheinlich ist es ein Out of Memory Fehler im Backend.

**Comment by anjunar** [comment]
Fixed in version 1.02 alpha

**Comment by FireFoxX79** [comment]
Im Nachtest ok.
