### ISSUE TITLE
Versionsnummer auf den Tabreiter Stimmt nicht mit der Versionsnummer der Seite überein

### ISSUE THREAD

**Issue by FireFoxX79** [anjunar/blomst-parent#24]
Ob die Versionsnummer auf dem Tab wirklich vorhanden sein muss überlass ich dir als Design Entscheidung. Nur wenn sie drauf ist sollten Sie identisch sein.
![image](https://user-images.githubusercontent.com/115038502/195160728-c2379987-bfc0-44e1-915b-a1fce5514a18.png)

**Comment by anjunar** [comment]
Fixed in version 1.04

**Comment by FireFoxX79** [comment]
Im Test OK.
